# clean

MAKEFLAGS += --no-print-directory
BOOTSTRAPMAKE = bootstrap.mk
TMPFILE = mkc-tmp.txt

INST_BIN_DIR = $(DESTDIR)$(PREFIX)/bin
INST_TMPL_DIR = $(DESTDIR)$(PREFIX)/share/mkc/templates
INST_SHR_INC_DIR = $(DESTDIR)$(PREFIX)/share/mkc/include

# if the bootstrap has been run, then the Makefile will be
# populated with the mkc generated output, and the mkc-all
# target will exist
.PHONY: all
all:
	@grep '^mkc-all' Makefile >/dev/null 2>&1; rc=$$?; \
	if [ $$rc -eq 0 ]; then \
	  $(MAKE) mkc-all; \
	else \
	  $(MAKE) bootstrap ; \
	fi

.PHONY: bootstrap
bootstrap:
	@$(MAKE) -f $(BOOTSTRAPMAKE) all

.PHONY: sanitize
sanitize:
	@$(MAKE) -f $(BOOTSTRAPMAKE) sanitize

# remove the generated files
.PHONY: distclean
distclean:
	@$(MAKE) realclean
	@-rm -f mkc_grammar.h mkc_grammar.c
	@-rm -f mkc_lex.h mkc_lex.c

# keep the files generated by bison and flex
# these will be shipped with a distribution
.PHONY: realclean
realclean:
	@$(MAKE) clean
	@-rm -f mkc_config.h
	@-rm -f z
	@-rm -f bootstrap.txt
	@# the tmp directory contains the bootstrap targets
	@-rm -rf tmp

.PHONY: clean
clean:
	@$(MAKE) tclean
	@-rm -f *.o
	@-rm -f mkc
	@-rm -rf mkc_files

.PHONY: tclean
tclean:
	@-find . -name '*.orig' -print | xargs rm -f
	@-find . -name '*~' -print | xargs rm -f
	@-rm -f w ww www *.orig asan.* core.*
	@-rm -f mkc_grammar.output *.mk.bak
	@-rm -f tests/tmp/*
	@-rm -f dep-*.txt

# depend for bootstrap makefile

.PHONY: depend
depend:
	-makedepend -f $(BOOTSTRAPMAKE) \
	    -DMKC_BOOTSTRAP=1 -Iinclude *.c 2>/dev/null
	cat $(BOOTSTRAPMAKE) | \
	    sed -e 's,[/]usr[/]include[/][^ ]*,,g' \
	        -e '/^[a-z][a-z_]*\.o:[ ]*$$/ d' \
	    > $(BOOTSTRAPMAKE).n
	mv $(BOOTSTRAPMAKE).n $(BOOTSTRAPMAKE)

.PHONY: partialobj
partialobj:
	echo 'PARTIALOBJ = \\' > $(TMPFILE)
	grep -l 'include "mkc_config.h' *.c | \
	    sed -e 's,\.c$$,\.o,' \
	        -e 's,^,\t,' \
	        -e '$$ ! s,$$, \\,' \
	    >> $(TMPFILE)
	echo '' >> $(TMPFILE)
	cat $(BOOTSTRAPMAKE) | \
	    sed -e '/^PARTIALOBJ/,/^$$/ d' | \
	    sed -e '/^# PARTIALOBJ/ r $(TMPFILE)' \
	    > $(BOOTSTRAPMAKE).n
	mv $(BOOTSTRAPMAKE).n $(BOOTSTRAPMAKE)
	rm -f $(TMPFILE)

.PHONY: test-install
test-install:
	@if [ "$(PREFIX)" = "" ]; then echo "No prefix set"; exit 1; fi
	@$(MAKE) tclean
	mkdir -p $(INST_BIN_DIR)
	mkdir -p $(INST_TMPL_DIR)
	mkdir -p $(INST_SHR_INC_DIR)
	cp -f mkc $(INST_BIN_DIR)
	cp include/mkc_def.h $(INST_SHR_INC_DIR)
	cp include/mkc_compiler.h $(INST_SHR_INC_DIR)
	cp templates/* $(INST_TMPL_DIR)

# MKC DO NOT DELETE
