/*
 * Copyright 2026 Brad Lanam Pleasant Hill CA
 */

#include "mkc_asttoken.h"

char const * const typenames [MKC_T_MAX] = {
  [MKC_T_ATTR_COMPILER] = "compiler",
  [MKC_T_ATTR_COMP_FLAGS] = "compiler_flags",
  [MKC_T_ATTR_CONTEXT] = "context",
  [MKC_T_ATTR_DEFINE_ZERO] = "define_zero",
  [MKC_T_ATTR_HEADER] = "header",
  [MKC_T_ATTR_INPUT] = "input",
  [MKC_T_ATTR_LINK_FLAGS] = "link_flags",
  [MKC_T_ATTR_METHOD] = "method",
  [MKC_T_ATTR_NAME] = "name",
  [MKC_T_ATTR_NEGATE] = "negate",
  [MKC_T_ATTR_OUTPUT] = "output",
  [MKC_T_ATTR_SOURCE] = "source",
  [MKC_T_CHK_COMP_FLAG] = "compiler_flag",
  [MKC_T_CHK_CONST] = "constant",
  [MKC_T_CHK_DEFINE] = "define",
  [MKC_T_CHK_FUNCTION] = "function",
  [MKC_T_CHK_LINK_FLAG] = "link flag",
  [MKC_T_CHK_PACKAGE] = "package",
  [MKC_T_CHK_SIZE] = "size",
  [MKC_T_CHK_STRUCT_MEMBER] = "struct_member",
  [MKC_T_CHK_TYPE] = "type",
  [MKC_T_ID_FILE_NAME] = "id_file_name",
  [MKC_T_ID_PATH_NAME] = "id_path_name",
  [MKC_T_ID_VAR_NAME] = "id_var_name",
  [MKC_T_LOOP_BREAK] = "break",
  [MKC_T_LOOP_CONTINUE] = "continue",
  [MKC_T_MAIN] = "main",
  [MKC_T_OP_AND] = "op_and",
  [MKC_T_OP_DIVIDE] = "op_divide",
  [MKC_T_OP_MINUS] = "op_minus",
  [MKC_T_OP_MODULO] = "op_modulo",
  [MKC_T_OP_MULTIPLY] = "op_multiply",
  [MKC_T_OP_NOT] = "op_not",
  [MKC_T_OP_NUM_EQ] = "op_num_eq",
  [MKC_T_OP_NUM_GE] = "op_num_ge",
  [MKC_T_OP_NUM_GT] = "op_num_gt",
  [MKC_T_OP_NUM_LE] = "op_num_le",
  [MKC_T_OP_NUM_LT] = "op_num_lt",
  [MKC_T_OP_NUM_NE] = "op_num_ne",
  [MKC_T_OP_OR] = "op_or",
  [MKC_T_OP_PLUS] = "op_plus",
  [MKC_T_OP_STR_EQ] = "op_str_eq",
  [MKC_T_OP_STR_GE] = "op_str_ge",
  [MKC_T_OP_STR_GT] = "op_str_gt",
  [MKC_T_OP_STR_LE] = "op_str_le",
  [MKC_T_OP_STR_LT] = "op_str_lt",
  [MKC_T_OP_STR_NE] = "op_str_ne",
  [MKC_T_OP_UNARY_MINUS] = "op_unary_minus",
  [MKC_T_OP_UNARY_PLUS] = "op_unary_plus",
  [MKC_T_STMTLIST] = "stmtlist",
  [MKC_T_STMT_CONFIGURE] = "stmt_configure",
  [MKC_T_STMT_DEBUG] = "stmt_debug",
  [MKC_T_STMT_ELSEIF] = "stmt_elseif",
  [MKC_T_STMT_FOREACH] = "stmt_foreach",
  [MKC_T_STMT_FUNCTION] = "stmt_function",
  [MKC_T_STMT_IF] = "stmt_if",
  [MKC_T_STMT_LOADCACHE] = "stmt_load_cache",
  [MKC_T_STMT_MARK] = "stmt_mark",
  [MKC_T_STMT_PRINT] = "stmt_print",
  [MKC_T_STMT_SET] = "stmt_set",
  [MKC_T_STMT_PROFILE] = "stmt_profile",
  [MKC_T_STMT_PROJECT] = "stmt_project",
  [MKC_T_STMT_WHILE] = "stmt_while",
  [MKC_T_VAL_ENV_VARIABLE] = "val_env_variable",
  [MKC_T_VAL_FALSE] = "val_false",
  [MKC_T_VAL_INTEGER] = "val_integer",
  [MKC_T_VAL_LIST] = "val_list",
  [MKC_T_VAL_QUOTED_STRING] = "val_quoted_string",
  [MKC_T_VAL_STATIC_STRING] = "val_static_string",
  [MKC_T_VAL_TRUE] = "val_true",
  [MKC_T_VALUE] = "value",
  [MKC_T_VARIABLE] = "variable",
};

